[world]
name = "Contagion"
seed = "contagion"

[namespace]
default = "contagion"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia"
account_address = "0x069c57ba0814d68fd488621927bd297d317cb0fc2ab91107cc5409812fa268c7"
private_key = "0x0058fbbb54ad6282deb91ce8b6a6142eea3b62352926e97ad99e5e4897b3068f"

[writers]
"contagion" = ["contagion-contagion_actions"]
